### ISSUE TITLE
balenaPhono keeps loop restarting

### ISSUE THREAD

**Issue by nickstrijbos** [SamEureka/balenaPhono#8] opened 2023-05-23 18:24 UTC
Hi I want to use this on my raspberri Pi 4. It shows that it found a USB device. But still gives a connector error with darkice: DarkIce: DarkIce.cpp:1273: can't open connector [0]. (changed all the different types of plughw:1,0 and plughw:0,0. I want to troubleshoot it but because it keeps restarting the containers I cannot check it... Hope you can help 

![image](https://github.com/SamEureka/balenaPhono/assets/7068866/f039e17a-ec97-485a-bf74-4985c40dd46e)

**Comment by SamEureka** [comment] 2023-05-25 15:36
@nickstrijbos 

I will be happy to help you troubleshoot. I won't be available until next Tuesday (May30) though. In the interim, could you provide the list of hardware you are using. This will help me understand the problem. Also, did you push the project using `balena push` or use the 'Deploy with Balena' button?

See you Tuesday!

//Sam

**Comment by nickstrijbos** [comment] 2023-05-26 07:34
Hey @SamEureka!

Thanks for your quick response. I am using a Raspberry Pi 4 with a Audio-Technica LP120XBT-USB. I just tried something else with just a barebone debian install and installed darkice and icecast. And it works. But I loved the idea with Balena. I did push the project using the Deploy with Balena button. Hope this helps. And see speak to you on tuesday.

Cheers Nick

**Comment by SamEureka** [comment] 2023-05-31 13:11
Hello @nickstrijbos 

I can't get the error to reproduce on my hardware. I run it daily on a Pi Zero W and it has been working perfectly for a few months. I just tried it on a Pi4 4GB and got the same positive results.

### There are a couple things to try. 

- One: Push the repo to your balena fleet using the balena-cli with the `balena push <fleet name>` command and see if that makes any difference. --> [Install Cli](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md) | [balena push](https://docs.balena.io/learn/deploy/deployment/#balena-push)
- Two is add the device variable `DARKICE_DEVICE` and play with variations of the hardware config as the value.

- [ ] plughw0,1
- [ ] plughw0,2
- [ ] hw0,1
- [ ] hw0,2
- [ ] default

It will be a lot of rebooting but the pi4 is pretty fast.

### --- More troubleshooting ---

You are getting past the soundcard check that is hard coded to `/proc/asound/card0`, so your sound drivers are loading something.

Since the balenaPhono container keeps crash looping we can possibly look at the Host OS Terminal in the balena dashboard to give us some clues.

Open the Host OS terminal and try these commands. I'll provide the output from my balenaPhono device below each command.


> `# cat /proc/asound/devices`
``` 
0: [ 0]   : control
16: [ 0- 0]: digital audio playback
24: [ 0- 0]: digital audio capture
33:        : timer
```

> `# cat /proc/asound/cards`
```
0 [CODEC          ]: USB-Audio - USB AUDIO  CODEC
                      BurrBrown from Texas Instruments USB AUDIO  CODEC at usb-20980000.usb-1, full s
```
What we are looking for is the number assigned to the card. In my case it is 0 (indicated by this: `0 [CODEC ] ...`)

### Random thoughts
If you have it working by direct install maybe that can give us some clues to what is going on. 

What versions of Debian, Icecast, Darkice are you using. If you have it up, try those commands to see what the output is. Also the darkice.cfg on the one you have working might tell us what to change in the balena build/config to get the balena app working for you.

Regards,
//Sam

**Comment by nickstrijbos** [comment] 2023-06-19 09:06
Hi Sam,

I got some bad news :(
I no longer have access to the raspberry pi4. because it had to work for audio streaming from the TV to the sonos speakers. With this one it now hangs permanently on the office TV with the baremetal system. I was still wondering if we had an extra Pi4 but this was not the case. So unfortunately I cannot troubleshoot it further either. Although this would have been fun for me. nevertheless I want to thank you very much for the effort you took and thus your free time. Should I have another raspberry Pi 4 in the near future I would certainly like to test what you have mentioned above.

Regards,
Nick

**Comment by SamEureka** [comment] 2023-12-12 17:51
@nickstrijbos,
 
Just wanted to let you know that I updated the code to work better with Raspberry Pi 4 devices. If you ever want to take another crack at this project, put in another issue and I would be happy to help if I can.

Regards,
//Sam

**Closed by SamEureka** 2023-12-12 17:51 UTC
